In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.32155253, 0.63083022, 0.29790977, 0.92146638, 0.9015109 ,
       0.16248359, 0.58675102, 0.8617998 , 0.27074229, 0.39910036,
       0.35126973, 0.97896171, 0.82398932, 0.45828989, 0.46370261,
       0.65107888, 0.15035037, 0.40672128, 0.89838399, 0.0745423 ,
       0.33580331, 0.93884639, 0.8932451 , 0.59647219, 0.41093381,
       0.54993974, 0.44998034, 0.2108066 , 0.29721615, 0.24618475,
       0.74439473, 0.29375926, 0.43138468, 0.12993259, 0.9575387 ,
       0.57141318, 0.14287433, 0.08114221, 0.44220166, 0.37593382,
       0.23486828, 0.13414659, 0.99033065, 0.86858588, 0.40339436,
       0.47337069, 0.44854988, 0.7990209 , 0.69870562, 0.1019355 ,
       0.54275524, 0.4350609 , 0.22249057, 0.22692897, 0.85724842,
       0.08982738, 0.18115034, 0.22686844, 0.92477509, 0.3187902 ,
       0.75414072, 0.57486913, 0.11844641, 0.69659348, 0.1490882 ,
       0.03301728, 0.61263997, 0.53182729, 0.81792276, 0.63545892,
       0.70425595, 0.10942596, 0.27600643, 0.81291324, 0.87417

In [3]:
np.sum?

In [7]:
X = np.arange(27).reshape(3,3,3)
X

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
np.sum(X,axis=(0,1))

array([108, 117, 126])